### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by pavan-kumar-99**

### CODE REVIEW

**Comment by pavan-kumar-99** [comment]
Ran Plan for project: `ec2` dir: `ec2` workspace: `default`

<details><summary>Show Output</summary>

```diff
In Terraform Init and Plan


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_instance.web will be created
+ resource "aws_instance" "web" {
      + ami                                  = "ami-0851b76e8b1bce90b"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = "ap-south-1b"
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "t3.large"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = (known after apply)
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + subnet_id                            = (known after apply)
      + tags                                 = {
          + "Name" = "HelloAtlantis"
        }
      + tags_all                             = {
          + "Name" = "HelloAtlantis"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + user_data_replace_on_change          = false
      + vpc_security_group_ids               = (known after apply)

      + capacity_reservation_specification {
          + capacity_reservation_preference = (known after apply)

          + capacity_reservation_target {
              + capacity_reservation_id = (known after apply)
            }
        }

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + enclave_options {
          + enabled = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
          + instance_metadata_tags      = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p ec2`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-0:4141/lock?id=pavan-kumar-99%252Fmedium-manifests%252Fec2%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p ec2`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by pavan-kumar-99** [comment]
atlantis apply

**Comment by pavan-kumar-99** [comment]
Ran Apply for project: `ec2` dir: `ec2` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by infa-pavakuma — APPROVED** [review]

**Comment by pavan-kumar-99** [comment]
atlantis apply

**Comment by pavan-kumar-99** [comment]
Ran Apply for project: `ec2` dir: `ec2` workspace: `default`

```diff
In Terraform Apply

aws_instance.web: Creating...
aws_instance.web: Still creating... [10s elapsed]
aws_instance.web: Creation complete after 12s [id=i-01310312a9c2495e1]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.


```

**Comment by pavan-kumar-99** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by pavan-kumar-99** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `ec2` workspace: `default`

**Pull request merged**
